<h3>Building a Neural Network from scratch in PyTorch</h3><hr>
<p><small>Time to get started with Neural Networks!</small></p>

In [43]:
input_tensor = torch.Tensor([[1, 0, 1, 0], [1, 0, 1, 1], [0, 1, 0, 1]])
output_tensor = torch.Tensor([[1], [1], [0]])
print(input_tensor, "\n")
print(output_tensor)

tensor([[1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 1., 0., 1.]]) 

tensor([[1.],
        [1.],
        [0.]])


In [0]:
# sigmoid function
def sigmoid(x):
  return 1/(1 + torch.exp(-x))

# derivative of the sigmoid function
def derivatives_sigmoid(x):
  return sigmoid(x) * (1 - sigmoid(x))

In [0]:
# training iterations
epoch = 7000
lr = .1 #learning_rate

input_layer = input_tensor.shape[1]
hidden_layer = 3
output_neurons = 1

weight_hidden = torch.randn(input_layer, hidden_layer).type(torch.FloatTensor)
bias_hidden = torch.randn(1, hidden_layer).type(torch.FloatTensor)
weight_output = torch.randn(hidden_layer, output_neurons)
bias_output = torch.randn(1, output_neurons)

In [0]:
for i in range(epoch):
  # Forward propagation
  hidden_layer_activations = sigmoid(torch.mm(input_tensor, weight_hidden) + bias_hidden)
  output = sigmoid(torch.mm(hidden_layer_activations, weight_output) + bias_output)

  # Backpropagation
  error = output_tensor - output
  slope_output_layer = derivatives_sigmoid(output)
  slope_hidden_layer = derivatives_sigmoid(hidden_layer_activations)
  d_output = error * slope_output_layer
  error_at_hidden_layer = torch.mm(d_output, weight_output.t())
  d_hidden = error_at_hidden_layer * slope_hidden_layer
  weight_output += torch.mm(hidden_layer_activations.t(), d_output) * lr
  bias_output += d_output.sum() * lr
  weight_hidden += torch.mm(input_tensor.t(), d_hidden) * lr
  bias_hidden += d_output.sum() * lr

In [48]:
print("Actual: \n", output_tensor, "\n")
print("Predicted: \n", output)

Actual: 
 tensor([[1.],
        [1.],
        [0.]]) 

Predicted: 
 tensor([[0.9969],
        [0.9961],
        [0.0047]])
