<h3> Introduction to Tensors </h3><hr>
<p><small>Tensors are multidimensional arrays. And PyTorch tensors are similar to NumPy’s n-dimensional arrays. We can use these tensors on a GPU as well (this is not the case with NumPy arrays). This is a major advantage of using tensors.</small></p>
<p><small>PyTorch supports multiple type of Tensors</small></p>
<ul>
  <small>
    <li>FloatTensor: 32-bit float</li>
    <li>DoubleTensor: 64-bit float</li>
    <li>HalfTensor: 16-bit float</li>
    <li>IntTensor: 32-bit int</li>
    <li>LongTensor: 64-bit int</li>
  </small>
</ul>

In [0]:
# importing libraries
import numpy as np

import torch

In [2]:
# initializing variables

numpy_a = np.array(5)

torch_a = torch.tensor(5)

print(numpy_a)
print(torch_a)

5
tensor(5)


In [3]:
numpy_b = np.array(10)
torch_b = torch.tensor(10)

print("*******Numpy********")

print(numpy_a +  numpy_b)
print(numpy_a -  numpy_b)
print(numpy_a *  numpy_b)
print(numpy_a // numpy_b)

print("*******Tensors*********")

print(torch_a +  torch_b)
print(torch_a -  torch_b)
print(torch_a *  torch_b)
print(torch_a // torch_b)

*******Numpy********
15
-5
50
0
*******Tensors*********
tensor(15)
tensor(-5)
tensor(50)
tensor(0)


<h4>Working with Matrices </h4><hr>
<p><small>Operations with Matrices</small></p>

In [4]:
# operations on 3x3 matrix

numpy_a = np.zeros((3, 3))
torch_a = torch.zeros((3, 3))

# We have specified the random seed at the beginning here so that every time we run the code, 
# the same random number will generate
np.random.seed(42)
random_numpy_a = np.random.randn(3, 3)
print(random_numpy_a, "\n")

torch.manual_seed(42)
random_torch_a = torch.randn(3, 3)
print(random_torch_a)

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]] 

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])


In [5]:
random_numpy_b = np.random.randn(3, 3)
random_torch_b = torch.randn(3, 3)

print(np.add(random_numpy_a, random_numpy_b), '\n')
print(np.subtract(random_numpy_a, random_numpy_b), '\n')
print(np.dot(random_numpy_a, random_numpy_b), '\n')
print(np.divide(random_numpy_a, random_numpy_b), '\n')
print(np.transpose(random_numpy_a), "\n")

print(torch.add(random_torch_a, random_torch_b), '\n')
print(torch.sub(random_torch_a, random_torch_b), '\n')
print(torch.mm(random_torch_a, random_torch_b), '\n')
print(torch.div(random_torch_a, random_torch_b), '\n')
print(torch.t(random_torch_a))

[[ 1.0392742  -0.60168199  0.18195878]
 [ 1.76499213 -2.14743362 -1.95905479]
 [ 1.01692529 -0.24539639 -0.15522705]] 

[[-0.04584589  0.32515339  1.11341829]
 [ 1.28106758  1.67912687  1.49078088]
 [ 2.14150034  1.78026585 -0.78372172]] 

[[-0.12814468 -0.62164688  0.21069439]
 [ 0.90133115 -0.02065676 -0.3790019 ]
 [ 1.30648762 -1.7246546  -2.20677932]] 

[[ 0.9155008   0.29835784 -1.39069607]
 [ 6.29449313  0.12238321  0.13573803]
 [-2.80855031 -0.75771243 -1.49396459]] 

[[ 0.49671415  1.52302986  1.57921282]
 [-0.1382643  -0.23415337  0.76743473]
 [ 0.64768854 -0.23413696 -0.46947439]] 

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]]) 

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]]) 

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]]) 

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.

In [6]:
# concatenating tensors
print(torch.cat((random_torch_a, random_torch_b)), "\n")

print(torch.cat((random_torch_a, random_torch_b), dim=1), "\n")

# c = random_torch_a.reshape(1, 9)
# print(c)
# c.reshape(3, 3)
c = torch.randn((3, 3), requires_grad=True)
print(c)
c.mean().backward()

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094],
        [ 1.1103, -1.6898, -0.9890],
        [ 0.9580,  1.3221,  0.8172]]) 

tensor([[ 0.3367,  0.1288,  0.2345,  0.2674,  0.5349,  0.8094],
        [ 0.2303, -1.1229, -0.1863,  1.1103, -1.6898, -0.9890],
        [ 2.2082, -0.6380,  0.4617,  0.9580,  1.3221,  0.8172]]) 

tensor([[-0.7658, -0.7506,  1.3525],
        [ 0.6863, -0.3278,  0.7950],
        [ 0.2815,  0.0562,  0.5227]], requires_grad=True)
